spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: aad9fffaff5b6655b991487c5ff8b445
            client-secret: 37LPXBI0nSPFU8bulkKESIb9aUXHIWQu
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authorization-method: client_secret_post
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email



        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-url: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  application:
    name: drinks
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss
  mail:
    host: smtp.gmail.com
    port: 587
    username: hwangdonggeun70@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 120  # 30 * 60 * 1000 == 30?
  image:
    default_src:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
jwt:
  signkey: N1Y8VjG7aKNHXbPR1Pqa6FIBo9S5oy3zGEP6ErJ1P5Ua
  expiration: 3000

